ARG VERSION=2
FROM arm64v8/caddy:${VERSION}-alpine

COPY ./arm64/caddy_arm64 /usr/bin/caddy
RUN chmod +x /usr/bin/caddy

LABEL org.opencontainers.image.authors="github.com/alexandzors"
LABEL org.opencontainers.image.architecture="arm64"