name: Caddy
on:
  workflow_dispatch:
  repository_dispatch:
    types: Caddy
  workflow_run:
    workflows: ["Notify"]
    types:
      - completed

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,amd64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      # Install xcaddy for binary building
      - name: Get xcaddy tool
        run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

      - name: Pull Local Repo
        uses: actions/checkout@v4

      # Build Caddy binaries with xcaddy
      - name: Build Binaries
        run: |
          bash build.sh

      # Get caddy version from binarys and set version/tag info
      - name: Get Version
        id: caddy_version
        run: |
          CADDY=$(./amd64/caddy version)
          vr="${CADDY}"
          # Extract version and remove the 'v' from the version string for the 'version' variable
          VERSION=$(echo $vr | head -n1 | cut -d " " -f1 | sed 's/^v//')
          TAG=$( echo $vr | head -n1 | cut -d " " -f1 )
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Var Debug
        run: |
          echo "TAG: ${{ env.TAG }}"
          echo "VERSION: ${{ env.VERSION }}"

      # Get the latest caddy release notes from version tag
      - name: Get latest Caddy release notes
        id: get_release_notes
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.TAG }}
          repo: caddyserver/caddy

      # Create Binary release with release notes from upstream
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Caddy ${{ env.VERSION }}
          body: |
            **Caddy ${{ env.TAG }} release notes:**
            _[caddyserver/caddy](https://github.com/caddyserver/caddy/releases/tag/${{ env.TAG }})_
            ${{ steps.get_release_notes.outputs.body }}
          files: |
            amd64/caddy
            amd64/caddy.exe
            arm64/caddy_arm64
            darwin/caddy_darwin

      # Login to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USR }}
          password: ${{ secrets.DOCKER_HUB_PW }}

      # Build and push multi-arch Docker images
      - name: Build and Push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USR }}/caddy:${{ env.VERSION }}
            ${{ secrets.DOCKER_HUB_USR }}/caddy:latest
          build-args: |
            VERSION=${{ env.VERSION }}

      - name: Build and Push Docker SSH Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ssh
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USR }}/caddy:${{ env.VERSION }}-ssh
            ${{ secrets.DOCKER_HUB_USR }}/caddy:latest-ssh
          build-args: |
            VERSION=${{ env.VERSION }}